# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170807_1525'),
        ('seams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(to='login.Profile'),
        ),
    ]
