# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0002_auto_20170820_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
    ]
