# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0004_project_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='internalMeetingCreated',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='researchDone',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='saleDocLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='salePointsCreated',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='uniqueTempKey',
            field=models.CharField(default='myNull', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seams.Event'),
        ),
    ]
