# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0006_auto_20170820_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='uniqueTempKey',
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Add a description of the event!', max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
