# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0008_auto_20170820_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seams.Event'),
        ),
    ]
