# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0010_auto_20170821_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
