# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seams', '0015_auto_20170823_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
