# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0018_auto_20170823_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='eventtitle',
        ),
    ]
