# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0020_auto_20170823_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Add a description of the event!', max_length=750),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
