# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seams', '0021_auto_20170826_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.CharField(choices=[('E', 'Event'), ('T', 'Task')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
