# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seams', '0003_remove_project_participants'),
        ('login', '0002_auto_20170807_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(to='seams.Project'),
        ),
    ]
